/* Script-VM command handler: pull this command's operands out of the descriptor
 * array through the VM's typed fetchers, build a parameter block on the stack,
 * hand it to the overlay's builder, and post the result to
 * func_ov002_0207643c. Always reports success.
 *
 * Generated by tools/gen_vm_emit.py, which reads the shape straight off the
 * disassembly -- 19 functions share this skeleton and differ only in which
 * fetcher serves each slot, the descriptor offsets, and whether a slot is a word
 * or a byte.
 *
 * Two things the generator had to get right, both of which cost bytes when
 * wrong:
 *   - `adds r4, #N` advances the descriptor BASE and it STAYS advanced, so the
 *     last fetch reads descs+N, not descs.
 *   - the builder id is kept as a full word and truncated AT THE USE. Declaring
 *     it `unsigned short` truncates at the assignment instead and reorders two
 *     instructions on every member that fetches the id early.
 */
typedef struct {
    int nField00;            /* +0x00 */
    int nField04;            /* +0x04 */
    unsigned char bField08;   /* +0x08 */
    char pad09[3];
    int nField0c;            /* +0x0c */
    int nField10;            /* +0x10 */
    int nField14;            /* +0x14 */
    unsigned char bField18;   /* +0x18 */
    char pad19[3];
} Ov016EmitParams;          /* 0x1c */

extern int func_02021948(void *self, void *desc);
extern int func_02021980(void *self, void *desc);
extern int func_02021994(void *self, void *desc);
extern int func_ov016_02081f64(unsigned short id, Ov016EmitParams *params);
extern void func_ov002_0207643c(int target, int value);

int func_ov016_02081360(void *self, char *descs) {
    Ov016EmitParams params;
    int target;
    int id;

    params.nField00 = func_02021948(self, descs + 0x10);
    params.nField04 = func_02021994(self, descs + 0x18);
    params.bField08 = func_02021980(self, descs + 0x20);
    params.nField0c = func_02021994(self, descs + 0x28);
    params.nField10 = func_02021994(self, descs + 0x30);
    params.nField14 = func_02021994(self, descs + 0x38);
    params.bField18 = func_02021980(self, descs + 0x40);
    target = func_02021980(self, descs);
    id = func_02021980(self, descs + 0x8);
    func_ov002_0207643c(target, func_ov016_02081f64((unsigned short)id, &params));
    return 1;
}
