/* Script-VM command handler: pull this command's operands out of the descriptor
 * array through the VM's typed fetchers, build a parameter block on the stack,
 * hand it to the overlay's builder, and post the result to
 * func_ov002_0207643c. Always reports success.
 *
 * Generated by tools/gen_vm_emit.py, which reads the shape straight off the
 * disassembly -- 19 functions share this skeleton and differ only in which
 * fetcher serves each slot, the descriptor offsets, and whether a slot is a word
 * or a byte.
 *
 * Two things the generator had to get right, both of which cost bytes when
 * wrong:
 *   - `adds r4, #N` advances the descriptor BASE and it STAYS advanced, so the
 *     last fetch reads descs+N, not descs.
 *   - the builder id is kept as a full word and truncated AT THE USE. Declaring
 *     it `unsigned short` truncates at the assignment instead and reorders two
 *     instructions on every member that fetches the id early.
 */
typedef struct {
    int nField00;            /* +0x00 */
    int nField04;            /* +0x04 */
    int nField08;            /* +0x08 */
} Ov016EmitParams;          /* 0xc */

extern int func_02021948(void *self, void *desc);
extern int func_02021980(void *self, void *desc);
extern int func_02021994(void *self, void *desc);
extern int func_ov016_0207feb8(unsigned short id, Ov016EmitParams *params);
extern void func_ov002_0207643c(int target, int value);

int func_ov016_02080fa4(void *self, char *descs) {
    Ov016EmitParams params;
    int target;
    int id;

    target = func_02021980(self, descs);
    id = func_02021980(self, descs + 0x8);
    params.nField00 = func_02021948(self, descs + 0x10);
    params.nField04 = func_02021994(self, descs + 0x18);
    params.nField08 = func_02021994(self, descs + 0x20);
    func_ov002_0207643c(target, func_ov016_0207feb8((unsigned short)id, &params));
    return 1;
}
