/* func_ov201_020d2708 -- ov201's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * Source case order: 0, 1, 2, 8, 3, 4, 5, 6, 7, 9.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

extern void func_0203c634(int self, int slot, void (*cb)(void));
extern void func_ov201_020d296c(void);
extern void func_ov201_020d2a54(void);
extern void func_ov201_020d2c50(void);
extern void func_ov201_020d36a0(void);
extern void func_ov201_020d3804(void);
extern void func_ov201_020d2e34(void);
extern void func_ov201_020d3414(void);
extern void func_ov201_020d38cc(void);
extern void func_ov201_020d3b94(void);
extern void func_ov201_020d3dcc(void);

void func_ov201_020d2708(int self) {
    int *ctx;
    unsigned short v;

    ctx = *(int **)(self + 4);
    if (*(signed char *)(ctx[0] + 0x1c7) != -1) {
        *(signed char *)(ctx[0] + 0x1c6) = *(signed char *)(ctx[0] + 0x1c7);
        v = *(unsigned short *)(ctx[0] + 0x60);
        *(unsigned short *)(ctx[0] + 0x60) =
            (unsigned short)((v & ~0xff00)
                             | (((((unsigned int)v << 0x10) >> 0x18 | 0x40) << 0x18) >> 0x10));
        ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0x86;
        *(unsigned short *)(ctx[0] + 0x1ae) &= ~9;
        ((B8 *)(*(int *)(ctx[0] + 0x388) + 8))->f |= 1;

        switch (*(signed char *)(ctx[0] + 0x1c6)) {
        case 0:
            func_0203c634(self, 1, func_ov201_020d296c);
            break;
        case 1:
            func_0203c634(self, 1, func_ov201_020d2a54);
            break;
        case 2:
            func_0203c634(self, 1, func_ov201_020d2c50);
            break;
        case 8:
            func_0203c634(self, 1, func_ov201_020d36a0);
            break;
        case 3:
            func_0203c634(self, 1, func_ov201_020d3804);
            break;
        case 4:
            func_0203c634(self, 1, func_ov201_020d2e34);
            break;
        case 5:
            func_0203c634(self, 1, func_ov201_020d3414);
            break;
        case 6:
            func_0203c634(self, 1, func_ov201_020d38cc);
            break;
        case 7:
            func_0203c634(self, 1, func_ov201_020d3b94);
            break;
        case 9:
            func_0203c634(self, 1, func_ov201_020d3dcc);
            break;
        }
    }

    *(signed char *)(ctx[0] + 0x1c7) = -1;
}
