/* func_ov138_020d0890 -- ov138's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * The "nothing queued" case RETURNS outright (a predicated `popeq`).
 *
 * Source case order: 0, 1, 2, 4, 5, 6, 7, 3, 8.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

extern void func_0203c634(int self, int slot, void (*cb)(void));
extern void func_ov138_020d0ae4(void);
extern void func_ov138_020d0bb4(void);
extern void func_ov138_020d0d78(void);
extern void func_ov138_020d0e48(void);
extern void func_ov138_020d1250(void);
extern void func_ov138_020d133c(void);
extern void func_ov138_020d1640(void);
extern void func_ov138_020d19b4(void);
extern void func_ov138_020d1a7c(void);

void func_ov138_020d0890(int self) {
    int *ctx;

    ctx = *(int **)(self + 4);
    if (*(signed char *)(ctx[0] + 0x1c7) == -1) {
        return;
    }

    ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0xce;
    *(unsigned short *)(ctx[0] + 0x1ae) &= ~9;
    ((B8 *)(*(int *)(ctx[0] + 0x384) + 8))->f |= 1;
    *(unsigned short *)(ctx[0] + 0x1b0) = *(unsigned char *)((char *)ctx + 0x56);
    *(signed char *)(ctx[0] + 0x1c6) = *(signed char *)(ctx[0] + 0x1c7);

    switch (*(signed char *)(ctx[0] + 0x1c6)) {
    case 0:
        func_0203c634(self, 1, func_ov138_020d0ae4);
        break;
    case 1:
        func_0203c634(self, 1, func_ov138_020d0bb4);
        break;
    case 2:
        func_0203c634(self, 1, func_ov138_020d0d78);
        break;
    case 4:
        func_0203c634(self, 1, func_ov138_020d0e48);
        break;
    case 5:
        func_0203c634(self, 1, func_ov138_020d1250);
        break;
    case 6:
        func_0203c634(self, 1, func_ov138_020d133c);
        break;
    case 7:
        func_0203c634(self, 1, func_ov138_020d1640);
        break;
    case 3:
        func_0203c634(self, 1, func_ov138_020d19b4);
        break;
    case 8:
        func_0203c634(self, 1, func_ov138_020d1a7c);
        break;
    }

    *(signed char *)(ctx[0] + 0x1c7) = -1;
}
