/* func_ov160_020cccb8 -- ov160's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * The "nothing queued" case RETURNS outright (a predicated `popeq`).
 *
 * Source case order: 0, 1, 2, 4, 5, 6, 7, 3, 8.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

extern void func_0203c634(int self, int slot, void (*cb)(void));
extern void func_ov160_020ccf0c(void);
extern void func_ov160_020ccfdc(void);
extern void func_ov160_020cd1a0(void);
extern void func_ov160_020cd26c(void);
extern void func_ov160_020cd674(void);
extern void func_ov160_020cd760(void);
extern void func_ov160_020cda64(void);
extern void func_ov160_020cddd8(void);
extern void func_ov160_020cdea0(void);

void func_ov160_020cccb8(int self) {
    int *ctx;

    ctx = *(int **)(self + 4);
    if (*(signed char *)(ctx[0] + 0x1c7) == -1) {
        return;
    }

    ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0xce;
    *(unsigned short *)(ctx[0] + 0x1ae) &= ~9;
    ((B8 *)(*(int *)(ctx[0] + 0x388) + 8))->f |= 1;
    *(unsigned short *)(ctx[0] + 0x1b0) = *(unsigned char *)((char *)ctx + 0x56);
    *(signed char *)(ctx[0] + 0x1c6) = *(signed char *)(ctx[0] + 0x1c7);

    switch (*(signed char *)(ctx[0] + 0x1c6)) {
    case 0:
        func_0203c634(self, 1, func_ov160_020ccf0c);
        break;
    case 1:
        func_0203c634(self, 1, func_ov160_020ccfdc);
        break;
    case 2:
        func_0203c634(self, 1, func_ov160_020cd1a0);
        break;
    case 4:
        func_0203c634(self, 1, func_ov160_020cd26c);
        break;
    case 5:
        func_0203c634(self, 1, func_ov160_020cd674);
        break;
    case 6:
        func_0203c634(self, 1, func_ov160_020cd760);
        break;
    case 7:
        func_0203c634(self, 1, func_ov160_020cda64);
        break;
    case 3:
        func_0203c634(self, 1, func_ov160_020cddd8);
        break;
    case 8:
        func_0203c634(self, 1, func_ov160_020cdea0);
        break;
    }

    *(signed char *)(ctx[0] + 0x1c7) = -1;
}
