#!/usr/bin/env python3
"""Generate PROGRESS.md with transparent progress categories."""
from collections import Counter, defaultdict
from pathlib import Path
import re

import audit_progress

ROOT = Path(__file__).resolve().parents[1]
CATEGORY_ORDER = (
    "c_decompiled_matched",
    "asm_stub_matched",
    "sdk_identified",
    "named_only",
    "unknown_or_needs_review",
)


def keyf(unit):
    match = re.match(r"ov(\d+)", unit)
    return (1, int(match.group(1))) if match else (0, unit)


def status_mark(c_count, total):
    if c_count == total:
        return "DONE"
    if c_count:
        return "PART"
    return "TODO"


def main():
    functions, _unknown_sources = audit_progress.classify_functions()
    stats = defaultdict(Counter)

    for func in functions:
        stats[func["unit"]][func["category"]] += 1
        stats[func["unit"]]["total"] += 1

    lines = [
        "# Progress by module",
        "",
        "Auto-generated by `python tools/progress.py`.",
        "",
        "Only `C matched` counts as real C decompilation progress. ASM stubs and",
        "SDK/library identifications are tracked separately; see",
        "[docs/PROGRESS_POLICY.md](docs/PROGRESS_POLICY.md).",
        "",
        "| Module | C matched | ASM stubs | SDK id | Named only | Total | C % |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]

    totals = Counter()
    for unit in sorted(stats, key=keyf):
        row = stats[unit]
        total = row["total"]
        c_count = row["c_decompiled_matched"]
        for key in CATEGORY_ORDER:
            totals[key] += row[key]
        totals["total"] += total
        lines.append(
            "| {mark} {unit} | {c} | {asm} | {sdk} | {named} | {total} | {pct:.1f}% |".format(
                mark=status_mark(c_count, total),
                unit=unit,
                c=c_count,
                asm=row["asm_stub_matched"],
                sdk=row["sdk_identified"],
                named=row["named_only"],
                total=total,
                pct=100.0 * c_count / total if total else 100.0,
            )
        )

    total = totals["total"]
    c_total = totals["c_decompiled_matched"]
    lines.append(
        "| **TOTAL** | **{c}** | **{asm}** | **{sdk}** | **{named}** | **{total}** | **{pct:.1f}%** |".format(
            c=c_total,
            asm=totals["asm_stub_matched"],
            sdk=totals["sdk_identified"],
            named=totals["named_only"],
            total=total,
            pct=100.0 * c_total / total if total else 100.0,
        )
    )

    (ROOT / "PROGRESS.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(
        "PROGRESS.md -> "
        f"C={c_total}/{total} ({100.0 * c_total / total:.1f}%), "
        f"ASM={totals['asm_stub_matched']}, SDK={totals['sdk_identified']}"
    )


if __name__ == "__main__":
    main()
