#!/usr/bin/env python3
"""Generate PROGRESS.md with transparent progress categories."""
from collections import Counter, defaultdict
from pathlib import Path
import glob
import os
import re

import audit_progress

ROOT = Path(__file__).resolve().parents[1]
CATEGORY_ORDER = (
    "c_decompiled_matched",
    "asm_stub_matched",
    "sdk_identified",
    "named_only",
    "unknown_or_needs_review",
)


def keyf(unit):
    match = re.match(r"ov(\d+)", unit)
    return (1, int(match.group(1))) if match else (0, unit)


def status_mark(c_count, total):
    if c_count == total:
        return "DONE"
    if c_count:
        return "PART"
    return "TODO"


_SYM_RE = re.compile(r"(\S+)\s+kind:function\(\w+,\s*size=(0x[0-9a-fA-F]+)\)\s+addr:")


def compute_byte_progress():
    """Return (c_bytes, total_bytes) summed across every module's symbols.txt."""
    c_names = set()
    for path in glob.glob(str(ROOT / "src" / "**" / "*.c"), recursive=True):
        # asm_stubs are ASM blobs, and nonmatching/ is equivalent-but-unmatched C that is excluded
        # from the build entirely. Neither is byte-exact, so neither counts here -- this is the
        # metric the README calls the honest one. (nonmatching/ was silently counted until
        # 2026-07-17, which inflated it by every write-up ever parked.)
        if "asm_stubs" in path or "nonmatching" in path:
            continue
        c_names.add(os.path.basename(path)[:-2])  # strip .c

    total_bytes = 0
    c_bytes = 0
    for sym_path in glob.glob(str(ROOT / "config" / "arm9" / "**" / "symbols.txt"), recursive=True):
        with open(sym_path, encoding="utf-8") as fh:
            for line in fh:
                m = _SYM_RE.match(line)
                if not m:
                    continue
                name = m.group(1)
                size = int(m.group(2), 16)
                total_bytes += size
                if name in c_names:
                    c_bytes += size
    return c_bytes, total_bytes


def main():
    functions, _unknown_sources, _shared_overlay_copies = audit_progress.classify_functions()
    stats = defaultdict(Counter)

    for func in functions:
        stats[func["unit"]][func["category"]] += 1
        stats[func["unit"]]["total"] += 1

    lines = [
        "# Progress by module",
        "",
        "Auto-generated by `python tools/progress.py`.",
        "",
        "Only `C matched` counts as real C decompilation progress. ASM stubs and",
        "SDK/library identifications are tracked separately; see",
        "[docs/PROGRESS_POLICY.md](docs/PROGRESS_POLICY.md).",
        "",
        "| Module | C matched | ASM stubs | SDK id | Named only | Total | C % |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]

    totals = Counter()
    for unit in sorted(stats, key=keyf):
        row = stats[unit]
        total = row["total"]
        c_count = row["c_decompiled_matched"]
        for key in CATEGORY_ORDER:
            totals[key] += row[key]
        totals["total"] += total
        lines.append(
            "| {mark} {unit} | {c} | {asm} | {sdk} | {named} | {total} | {pct:.1f}% |".format(
                mark=status_mark(c_count, total),
                unit=unit,
                c=c_count,
                asm=row["asm_stub_matched"],
                sdk=row["sdk_identified"],
                named=row["named_only"],
                total=total,
                pct=100.0 * c_count / total if total else 100.0,
            )
        )

    total = totals["total"]
    c_total = totals["c_decompiled_matched"]
    lines.append(
        "| **TOTAL** | **{c}** | **{asm}** | **{sdk}** | **{named}** | **{total}** | **{pct:.1f}%** |".format(
            c=c_total,
            asm=totals["asm_stub_matched"],
            sdk=totals["sdk_identified"],
            named=totals["named_only"],
            total=total,
            pct=100.0 * c_total / total if total else 100.0,
        )
    )

    c_bytes, total_bytes = compute_byte_progress()
    byte_pct = 100.0 * c_bytes / total_bytes if total_bytes else 0.0
    lines.extend(
        [
            "",
            "## Byte progress",
            "",
            "Function-count percentages count each decomp'd function equally,",
            "which inflates progress when the decomp'd set is dominated by small",
            "trampolines and wrappers. The byte-based percentage below is closer",
            "to how decomp.dev reports progress:",
            "",
            "| C matched bytes | Total known bytes | % |",
            "|---:|---:|---:|",
            f"| **{c_bytes:,}** | **{total_bytes:,}** | **{byte_pct:.2f}%** |",
        ]
    )

    (ROOT / "PROGRESS.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(
        "PROGRESS.md -> "
        f"C={c_total}/{total} ({100.0 * c_total / total:.1f}%), "
        f"ASM={totals['asm_stub_matched']}, SDK={totals['sdk_identified']}, "
        f"bytes={c_bytes:,}/{total_bytes:,} ({byte_pct:.2f}%)"
    )


if __name__ == "__main__":
    main()
